spring:
    application:
        name: configdemo # The name of the application should match to the name of the config repo file
    config:
        import:
            - "optional:configserver:http://localhost:8888"
    cloud:
        config:
            label: dev 
    profiles:
        active: dev
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
build:
  id: ${BUILD_ID}
  version: ${BUILD_VERSION}
  name: ${BUILD_NAME}

